# Custom Language File for Launcher Customizer

[ejs.app]
title = "Lunex Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ci2bx/LunexLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "https://www.lunexmc.fr/"
mediaYouTubeURL = "https://www.lunexmc.fr/shop"
mediaDiscordURL = "https://discord.com/invite/Fm9NNVzqxx"

[ejs.settings]
sourceGithubLink = "https://github.com/ci2bx/LunexLauncher"
supportLink = "https://github.com/ci2bx/LunexLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR LUNEX"
welcomeDescription = "Rejoignez une communauté de joueurs passionnés par Minecraft et qui n'hésiteront pas à repousser les limites du jeu."
welcomeDescCTA = "Vous êtes a quelques clics de Lunex."
