[ejs.app]
title = "DreamClouds Studios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Shisuiicaro/Hasta-studios-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "https://zelthoriaismp.cloud"
mediaYouTubeURL = "https://www.tiktok.com/@_zsmp_"
mediaDiscordURL = "https://discord.gg/zsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/Shisuiicaro/Hasta-studios-Launcher"
supportLink = "https://github.com/Shisuiicaro/Hasta-studios-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenu sur le launcher des DreamClouds"
welcomeDescription = """
À partir de maintenant, ne te soucie plus d'installer Java, un modpack, puis de le mettre à jour car il ne marchait pas puis parce que Tegnew a changé d'avis

Pour au final arriver trop tard car il a deja tuer 36 dragons et finit tout son bouquin de magie

Découvre le luxe à ma Française, et à la sauce Funa
"""
